### ISSUE TITLE
外接显示器的问题

### ISSUE THREAD

**Issue by yijibin** [gxzzzzzzzzz/HP_zhan66_pro_14_g3#1]
感谢！确实可用，比较完美，但想求外界hdmi显示屏黑屏无信号的解决方案

**Comment by gxzzzzzzzzz** [comment]
您好！HDMI输出问题大概是macOS本身的兼容性问题，如果用apple的显示器应该没问题，其他的品牌可能会有不同表现，就我自己的外接显示器来说，插上可以自动识别，但是休眠唤醒后（或者开机前连接好显示器）黑屏（应该是没有检测到），后来在配置文件中PCI设备属性里增加<key>force-online</key>后，唤醒基本正常了，但是插拔会偶尔检测不到，你可以试试去掉这个foece-online看看有没有改善。另外可以尝试用hackintool定制edid看看有没有帮助。

**Comment by yijibin** [comment]
大佬你真的太厉害了！一下就给我解决了，感谢感谢！
